#!/usr/bin/env python3
"""Generate the standard HID Sensor reports used by the bridge.

The sensor interface has two input reports so WebHID can identify each
measurement by its HID Sensors usage page and report ID:
  report 1: angular velocity X/Y/Z (raw receiver gyro counts)
  report 2: acceleration X/Y/Z (4096 counts = 1 g)

The existing Vader2Pro gamepad interface stays byte-for-byte unchanged.
"""
import pathlib

D = []


def b(*xs):
    D.extend(xs)


def axis_report(report_id, sensor_usage, axis_usages, unit, exponent):
    b(0x05, 0x20)              # Usage Page (Sensors)
    b(0x09, sensor_usage)     # Motion: Gyrometer/Accelerometer 3D
    b(0xA1, 0x00)              # Physical collection
    b(0x85, report_id)         # Report ID
    b(0x05, 0x20)              # Data fields are also on Sensors page
    b(0x16, 0x00, 0x80)        # Logical Minimum (-32768)
    b(0x26, 0xFF, 0x7F)        # Logical Maximum (32767)
    b(0x75, 0x10)              # Report Size (16)
    b(0x95, 0x01)              # One value per usage
    for usage in axis_usages:
        b(0x0A, usage & 0xFF, (usage >> 8) & 0xFF)
        b(0x65, unit)          # Unit (degrees/s or g)
        b(0x55, exponent)      # Unit exponent
        b(0x81, 0x02)          # Input (Data,Var,Abs)
    b(0xC0)                    # End collection


# HID Usage Tables / HUTRR39 values:
# 0x76 = Motion: Gyrometer 3D; 0x73 = Motion: Accelerometer 3D.
# 0x0457..0x0459 = angular velocity X/Y/Z.
# 0x0453..0x0455 = acceleration X/Y/Z.
axis_report(1, 0x76, (0x0457, 0x0458, 0x0459), 0x15, 0x00)
axis_report(2, 0x73, (0x0453, 0x0454, 0x0455), 0x1A, 0x04)

out = pathlib.Path(__file__).with_name("desc_sensor.hex")
out.write_text("\n".join(
    " ".join(f"{x:02x}" for x in D[i:i + 16])
    for i in range(0, len(D), 16)
) + "\n")

hdr = pathlib.Path(__file__).with_name("desc_sensor.h")
hdr.write_text(
    "/* Auto-generated by hid_desc_sensor.py. */\n"
    "#pragma once\n#include <stdint.h>\n\n"
    f"static const uint8_t kDescSensor[{len(D)}] = {{\n"
    + "".join(
        "    " + ", ".join(f"0x{x:02x}" for x in D[i:i + 12]) + ",\n"
        for i in range(0, len(D), 12)
    )
    + "};\n"
    "#define SENSOR_DESC_REPORT_BYTES 6\n"
    "#define SENSOR_GYRO_REPORT_ID 1\n"
    "#define SENSOR_ACCEL_REPORT_ID 2\n"
)

print(f"传感器描述符 {len(D)} 字节 / 每个输入报告 6 字节")
print(" ".join(f"{x:02x}" for x in D))
